name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also, what did you expect to happen?
      placeholder: A bug happened when I...
    validations:
      required: true
  - type: textarea
    id: Reproduce
    attributes:
      label: How can the bug be reproduced?
      description: Also tell us your system's specifications if possible
      placeholder: In order to repeat this bug you can...
    validations:
      required: false
  - type: dropdown
    id: Rversion
    attributes:
      description: What version of R are you running?
      multiple: false
      options:
        - 4.4.0 (April, 2024)
        - 4.3.3 (February, 2024)
        - 4.3.2 (October, 2023)
        - 4.3.1 (June, 2023)
        - 4.3.0 (April, 2023)
        - 4.2.3 (March, 2023)
        - 4.2.2 (October, 2022)
        - 4.2.1 (June, 2022)
        - 4.2.0 (April, 2022)
        - 4.1.3 (March, 2022)
        - 4.1.2 (November, 2021)
        - 4.1.1 (August, 2021)
        - 4.1.0 (May, 2021)
        - 4.0.5 (March, 2021)
        - 4.0.4 (February, 2021)
        - 4.0.3 (October, 2020)
        - 4.0.2 (June, 2020)
        - 4.0.1 (June, 2020)
        - 4.0.0 (April, 2020)
        - Older than 4.0.0
    validations:
      required: true
  - type: dropdown
    id: Python-Version
    attributes:
      description: What version of Python are you running?
      multiple: false
      options:
        - 3.12
        - 3.11
        - 3.10
        - 3.9
        - 3.8
        - 3.7
        - 3.6
        - 3.5
        - 3.4
        - Older than 3.4
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
